// Mocks generated by Mockito 5.4.4 from annotations
// in prueba_tecnica/test/src/feature/home/data/home_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:api_sdk/api_sdk.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:prueba_tecnica/src/feature/home/data/repositories/home_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseApiSdk_0 extends _i1.SmartFake
    implements _i2.ResponseApiSdk {
  _FakeResponseApiSdk_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BooksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class BooksRepositoryMock extends _i1.Mock implements _i3.BooksRepository {
  @override
  _i4.Future<_i2.ResponseApiSdk> getNew() => (super.noSuchMethod(
        Invocation.method(
          #getNew,
          [],
        ),
        returnValue: _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #getNew,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #getNew,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ResponseApiSdk>);

  @override
  _i4.Future<_i2.ResponseApiSdk> getDetail(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #getDetail,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #getDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ResponseApiSdk>);

  @override
  _i4.Future<_i2.ResponseApiSdk> searchBook(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBook,
          [query],
        ),
        returnValue: _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #searchBook,
            [query],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ResponseApiSdk>.value(_FakeResponseApiSdk_0(
          this,
          Invocation.method(
            #searchBook,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.ResponseApiSdk>);
}
